name: Dependency sanity checker

on:
  push:
    branches: [main, release/**]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  validate-rust-git-rev-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stellar/actions/rust-check-git-rev-deps@main
